version: "3.8"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: pandemiccms
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: pandemiccms
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  pandemiccms:
    build:
      context: .
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_MASTER_KEY: 0fa8098c8e652a8a7c2bb448bb11ff54
    volumes:
      - log_data:/app/logs
      - storage_data:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
volumes:
  mariadb_data:
  log_data:
  storage_data:
